### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by aquiladvx** [42-Iniciativa-Open-Source/backend#2]
A API não está retornando as informações de **paginação** no Header como a API da 42 faz.

Informações retornadas hoje:

```
Connection: keep-alive
Server: gunicorn/20.0.4
Date: Sun, 20 Dec 2020 00:04:50 GMT
Content-Type: application/json
Content-Length: 44
Via: 1.1 vegur
```

https://api.intra.42.fr/apidoc/guides#pagination

**Comment by caio-vinicius** [comment]
Obrigado por reportar, Davi! I'm working on it ;).

**Comment by caio-vinicius** [comment]
Now, everything is working fine ;)
